#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\Git\herbert\Firmware\fpga\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/Xilinx/10.1/EDK
NON_CYG_XILINX_EDK_DIR = C:/Xilinx/10.1/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = spartan3a

DEVICE = xc3s1400afg676-4

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) \
                   $(MICROBLAZE_0_LIBG_OPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error no

BOOTLOADER_OUTPUT_DIR = firmware
BOOTLOADER_OUTPUT = $(BOOTLOADER_OUTPUT_DIR)/bootloader.elf

APPLICATION_OUTPUT_DIR = firmware
APPLICATION_OUTPUT = $(APPLICATION_OUTPUT_DIR)/app.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(BOOTLOADER_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(BOOTLOADER_OUTPUT) 

ALL_USER_ELF_FILES = $(BOOTLOADER_OUTPUT) $(APPLICATION_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X C:/Git/herbert/Firmware/fpga/ -E C:/Git/herbert/Firmware/fpga/


LIBRARIES =  \
       microblaze_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = bootloader_programclean application_programclean 

CORE_STATE_DEVELOPMENT_FILES = C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\proc_common_pkg.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\ipif_pkg.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\or_muxcy.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\or_gate128.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\family_support.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\pselect_f.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\proc_common_v2_00_a\hdl\vhdl\counter_f.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\plbv46_slave_single_v1_00_a\hdl\vhdl\plb_address_decoder.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\plbv46_slave_single_v1_00_a\hdl\vhdl\plb_slave_attachment.vhd \
C:\Xilinx\10.1\EDK\hw\XilinxProcessorIPLib\pcores\plbv46_slave_single_v1_00_a\hdl\vhdl\plbv46_slave_single.vhd \
C:\Git\herbert\Firmware\fpga\pcores\motor_controller_v1_00_a\hdl\vhdl\user_logic.vhd \
C:\Git\herbert\Firmware\fpga\pcores\motor_controller_v1_00_a\hdl\vhdl\motor_controller.vhd \
C:\Git\herbert\Firmware\fpga\pcores\lcd_controller_v1_00_a\hdl\vhdl\user_logic.vhd \
C:\Git\herbert\Firmware\fpga\pcores\lcd_controller_v1_00_a\hdl\vhdl\lcd_controller.vhd \
C:\Git\herbert\Firmware\fpga\pcores\spi_controller_v1_00_a\hdl\vhdl\user_logic.vhd \
C:\Git\herbert\Firmware\fpga\pcores\spi_controller_v1_00_a\hdl\vhdl\spi_controller.vhd \
C:\Git\herbert\Firmware\fpga\pcores\system_controller_v1_00_a\hdl\vhdl\user_logic.vhd \
C:\Git\herbert\Firmware\fpga\pcores\system_controller_v1_00_a\hdl\vhdl\system_controller.vhd \
C:\Git\herbert\Firmware\fpga\pcores\relay_controller_v1_00_a\hdl\vhdl\user_logic.vhd \
C:\Git\herbert\Firmware\fpga\pcores\relay_controller_v1_00_a\hdl\vhdl\relay_controller.vhd \
C:\Git\herbert\Firmware\fpga\pcores\switch_controller_v1_00_a\hdl\vhdl\user_logic.vhd \
C:\Git\herbert\Firmware\fpga\pcores\switch_controller_v1_00_a\hdl\vhdl\switch_controller.vhd

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/ddr2_sdram_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/debug_module_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/debug_uart_wrapper.ngc \
implementation/sbc_uart_wrapper.ngc \
implementation/intc_wrapper.ngc \
implementation/pwm_wrapper.ngc \
implementation/sensor_a_spi_wrapper.ngc \
implementation/motor_wrapper.ngc \
implementation/motor2_wrapper.ngc \
implementation/led_spi_wrapper.ngc \
implementation/lcd_wrapper.ngc \
implementation/timer_wrapper.ngc \
implementation/config_flash_spi_wrapper.ngc \
implementation/user_flash_spi_wrapper.ngc \
implementation/spi_control_wrapper.ngc \
implementation/system_wrapper.ngc \
implementation/relay_wrapper.ngc \
implementation/switch_control_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION BOOTLOADER
#################################################################

BOOTLOADER_SOURCES = /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader/main.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader/comm.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader/serial.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader/stubs.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader/timer.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader/vectors.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/assert.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/AT45DB161D.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/conversion.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/crc32.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/errors.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/flash.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/interrupt.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/processor.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/reboot.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/sprintf.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/printf.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/spi.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/update.c 

BOOTLOADER_HEADERS = 

BOOTLOADER_CC = mb-gcc
BOOTLOADER_CC_SIZE = mb-size
BOOTLOADER_CC_OPT = -Os
BOOTLOADER_CFLAGS = -Wall -DBOOTLOADER
BOOTLOADER_CC_SEARCH = # -B
BOOTLOADER_LIBPATH = -L./microblaze_0/lib/ # -L
BOOTLOADER_INCLUDES = -I./microblaze_0/include/   -I./firmware/bootloader -I./firmware/common 
BOOTLOADER_LFLAGS = # -l
BOOTLOADER_LINKER_SCRIPT = /cygdrive/c/Git/herbert/Firmware/fpga/firmware/bootloader.ld
BOOTLOADER_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(BOOTLOADER_LINKER_SCRIPT) 
BOOTLOADER_CC_DEBUG_FLAG =  -g 
BOOTLOADER_CC_PROFILE_FLAG = # -pg
BOOTLOADER_CC_GLOBPTR_FLAG= # -mxl-gp-opt
BOOTLOADER_MODE = executable
BOOTLOADER_LIBG_OPT = -$(BOOTLOADER_MODE) microblaze_0
BOOTLOADER_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mhard-float -mxl-float-convert -mxl-float-sqrt -mxl-barrel-shift -mxl-pattern-compare -mno-xl-soft-div -mcpu=v7.10.d 
BOOTLOADER_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
BOOTLOADER_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
BOOTLOADER_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
BOOTLOADER_OTHER_CC_FLAGS= $(BOOTLOADER_CC_GLOBPTR_FLAG)  \
                  $(BOOTLOADER_CC_START_ADDR_FLAG) $(BOOTLOADER_CC_STACK_SIZE_FLAG) $(BOOTLOADER_CC_HEAP_SIZE_FLAG)  \
                  $(BOOTLOADER_CC_INFERRED_FLAGS)  \
                  $(BOOTLOADER_LINKER_SCRIPT_FLAG) $(BOOTLOADER_CC_DEBUG_FLAG) $(BOOTLOADER_CC_PROFILE_FLAG) 

#################################################################
# SOFTWARE APPLICATION APPLICATION
#################################################################

APPLICATION_SOURCES = /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/main.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/cache.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/comm.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/initialization.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/motion.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/os.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/serial.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/signal.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/startup.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/steppers.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/stepper_hw.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/timer.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/assert.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/AT45DB161D.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/conversion.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/crc16.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/crc32.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/errors.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/flash.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/interrupt.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/lcd.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/processor.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/reboot.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/spi.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/common/update.c /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app/relay.c 

APPLICATION_HEADERS = 

APPLICATION_CC = mb-gcc
APPLICATION_CC_SIZE = mb-size
APPLICATION_CC_OPT = -O0
APPLICATION_CFLAGS = -Wall
APPLICATION_CC_SEARCH = # -B
APPLICATION_LIBPATH = -L./microblaze_0/lib/ # -L
APPLICATION_INCLUDES = -I./microblaze_0/include/   -I./firmware/app -I./firmware/common 
APPLICATION_LFLAGS = # -l
APPLICATION_LINKER_SCRIPT = /cygdrive/c/Git/herbert/Firmware/fpga/firmware/app.ld
APPLICATION_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(APPLICATION_LINKER_SCRIPT) 
APPLICATION_CC_DEBUG_FLAG =  -g 
APPLICATION_CC_PROFILE_FLAG = # -pg
APPLICATION_CC_GLOBPTR_FLAG= # -mxl-gp-opt
APPLICATION_MODE = executable
APPLICATION_LIBG_OPT = -$(APPLICATION_MODE) microblaze_0
APPLICATION_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mhard-float -mxl-float-convert -mxl-float-sqrt -mxl-barrel-shift -mxl-pattern-compare -mno-xl-soft-div -mcpu=v7.10.d 
APPLICATION_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
APPLICATION_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
APPLICATION_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
APPLICATION_OTHER_CC_FLAGS= $(APPLICATION_CC_GLOBPTR_FLAG)  \
                  $(APPLICATION_CC_START_ADDR_FLAG) $(APPLICATION_CC_STACK_SIZE_FLAG) $(APPLICATION_CC_HEAP_SIZE_FLAG)  \
                  $(APPLICATION_CC_INFERRED_FLAGS)  \
                  $(APPLICATION_LINKER_SCRIPT_FLAG) $(APPLICATION_CC_DEBUG_FLAG) $(APPLICATION_CC_PROFILE_FLAG) 
