//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ReaderControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_READERCONTROL_DIALOG        102
#define IDD_DIALOG_TEMP_MONITOR         129
#define IDD_DIALOG_TEMPERATURE          129
#define IDB_BITMAP_BACKGROUND           130
#define IDD_DIALOG_MANUAL               131
#define IDB_BITMAP_HEATBLOCK            132
#define IDB_BITMAP_HEATEDLID            134
#define IDB_BITMAP_STOP                 135
#define IDD_DIALOG_MANUAL_PROTOCOL      136
#define IDD_DIALOG_ADD_SEGMENT          137
#define IDI_ICON_ITI_LARGE              138
#define IDI_ICON_ITI_SMALL              139
#define IDD_DIALOG_CAMERA               140
#define IDB_BITMAP_RED_ON               142
#define IDB_BITMAP_BLUE_OFF             143
#define IDB_BITMAP_BLUE_ON              144
#define IDB_BITMAP_CLEAR_OFF            145
#define IDB_BITMAP_CLEAR_ON             146
#define IDB_BITMAP_CRIMSON_OFF          147
#define IDB_BITMAP_CRIMSON_ON           148
#define IDB_BITMAP_GREEN_OFF            149
#define IDB_BITMAP_GREEN_ON             150
#define IDB_BITMAP_ORANGE_OFF           151
#define IDB_BITMAP_ORANGE_ON            152
#define IDB_BITMAP_RED_OFF              153
#define IDB_BITMAP_X                    155
#define IDD_DIALOG_SEGMENT_EDITOR       156
#define IDD_DIALOG1                     158
#define IDD_DIALOG_PROGRAM_EDITOR       159
#define IDD_DIALOG_IMAGE_EDITOR         165
#define IDD_DIALOG_CAMERA_CALIBRATION   166
#define IDD_DIALOG_FIRMWARE_UPGRADE     170
#define IDD_DIALOG_CALIBRATION          171
#define IDD_DIALOG_SYSTEM               173
#define IDD_DIALOG_PRB                  174
#define IDD_DIALOG_PCB                  174
#define IDD_DIALOG_SELF_TEST            176
#define IDD_DIALOG_DEVICE_TEST          177
#define IDD_DIALOG_IMAGE_DATA           178
#define IDD_DIALOG_FILE_NAMING_TOOL     182
#define IDD_DIALOG_DEBUG_CAPTURE        183
#define IDC_BUTTON_TEST                 1000
#define IDC_BUTTON_CONNECT              1000
#define IDC_BUTTON_STOP                 1001
#define IDC_TABS                        1002
#define IDC_COMBO_COMMPORT              1003
#define IDC_EDIT_MSG1                   1004
#define IDC_COMBO_MOTORPORT             1004
#define IDC_BUTTON_SEND1                1005
#define IDC_CHECK_AUTO_HEADER           1006
#define IDC_EDIT_OUTPUT                 1007
#define IDC_BUTTON_CLEAR_OUTPUT         1008
#define IDC_EDIT_MSG2                   1009
#define IDC_EDIT_TARGET_TEMP            1009
#define IDC_EDIT_BLOCK_TARGET_TEMP      1009
#define IDC_BUTTON_SEND2                1010
#define IDC_BUTTON_ENABLE_CONTROL       1010
#define IDC_BUTTON_ENABLE_BLOCK_CONTROL 1010
#define IDC_EDIT_LID_TARGET_TEMP        1011
#define IDC_EDIT_HEATED_LID_TEMP        1012
#define IDC_EDIT_HEATED_LID_CENTER_TEMP 1012
#define IDC_EDIT_MSG3                   1013
#define IDC_EDIT_TEMP_A1                1013
#define IDC_BUTTON_SEND3                1014
#define IDC_EDIT_TEMP_A2                1014
#define IDC_EDIT_MSG4                   1015
#define IDC_EDIT_TEMP_A3                1015
#define IDC_BUTTON_SEND4                1016
#define IDC_EDIT_TEMP_A4                1016
#define IDC_EDIT_MSG5                   1017
#define IDC_EDIT_TEMP_A5                1017
#define IDC_BUTTON_SEND5                1018
#define IDC_EDIT_TEMP_A6                1018
#define IDC_EDIT_TEMP_B1                1019
#define IDC_EDIT_TEMP_B2                1020
#define IDC_EDIT_MSG6                   1021
#define IDC_EDIT_TEMP_B3                1021
#define IDC_BUTTON_SEND6                1022
#define IDC_EDIT_TEMP_B4                1022
#define IDC_EDIT_MSG7                   1023
#define IDC_EDIT_TEMP_B5                1023
#define IDC_BUTTON_SEND7                1024
#define IDC_EDIT_TEMP_B6                1024
#define IDC_EDIT_MSG8                   1025
#define IDC_EDIT_TEMP_C1                1025
#define IDC_BUTTON_SEND8                1026
#define IDC_EDIT_TEMP_C2                1026
#define IDC_EDIT_MSG9                   1027
#define IDC_EDIT_TEMP_C3                1027
#define IDC_BUTTON_SEND9                1028
#define IDC_EDIT_TEMP_C4                1028
#define IDC_EDIT_MSG10                  1029
#define IDC_EDIT_TEMP_C5                1029
#define IDC_BUTTON_SEND10               1030
#define IDC_EDIT_TEMP_C6                1030
#define IDC_EDIT_MSG11                  1031
#define IDC_EDIT_TEMP_D1                1031
#define IDC_BUTTON_SEND11               1032
#define IDC_EDIT_TEMP_D2                1032
#define IDC_EDIT_MSG12                  1033
#define IDC_EDIT_TEMP_D3                1033
#define IDC_BUTTON_SEND12               1034
#define IDC_EDIT_TEMP_D4                1034
#define IDC_EDIT_TEMP_D5                1035
#define IDC_EDIT_TEMP_D6                1036
#define IDC_EDIT_TEMP_D7                1037
#define IDC_CHECK_POLL_TEMP             1037
#define IDC_STATIC_VERSION              1038
#define IDC_BUTTON_ENABLE_LID_CONTROL   1038
#define IDC_LIST_PROTOCOL               1039
#define IDC_EDIT_TEMP_HEATSINK          1039
#define IDC_BUTTON_ADD_SEGMENT          1040
#define IDC_EDIT_TEMP_HEATSINK2         1040
#define IDC_EDIT_TEMP_AMBIENT           1040
#define IDC_BUTTON_START                1041
#define IDC_EDIT_HEATED_LID_RING_TEMP   1041
#define IDC_LIST_PROGRAM                1042
#define IDC_EDIT_TIME                   1043
#define IDC_BUTTON_ADD_PROGRAM          1043
#define IDC_BUTTON_DELETE_SEGMENT       1044
#define IDC_BUTTON_MOVE_SEGMENT_UP      1045
#define IDC_BUTTON_MOVE_SEGMENT_DOWN    1046
#define IDC_BUTTON_EDIT_SEGMENT         1047
#define IDC_EDIT_ITERATIONS             1048
#define IDC_BUTTON_DELETE_PROGRAM       1048
#define IDC_BUTTON_SAVE                 1049
#define IDC_BUTTON_LOAD                 1050
#define IDC_BUTTON_CLEAR                1051
#define IDC_BUTTON_CLEAR_CMDS           1052
#define IDC_BUTTON_MOVE_PROGRAM_UP      1052
#define IDC_CHECK_LID_ENABLE            1053
#define IDC_BUTTON_MOVE_PROGRAM_DOWN    1053
#define IDC_EDIT_LID_TEMP               1054
#define IDC_BUTTON_EDIT_PROGRAM         1054
#define IDC_CAMERA_FRAME                1055
#define IDC_BUTTON_SAVE_AS              1055
#define IDC_CHECK_LED0                  1059
#define IDC_CHECK_LED1                  1060
#define IDC_CHECK_LED2                  1061
#define IDC_CHECK_LED3                  1062
#define IDC_BUTTON_LED_OFF              1064
#define IDC_RADIO_FILTER_0              1065
#define IDC_EDIT_EXPOSURE               1066
#define IDC_BUTTON_CAPTURE              1067
#define IDC_EDIT_PATH                   1068
#define IDC_COMBO_TYPE                  1069
#define IDC_RADIO_FILTER_1              1071
#define IDC_EDIT2                       1071
#define IDC_EDIT_COMMAND                1071
#define IDC_EDIT_ERROR_THRESHOLD        1071
#define IDC_EDIT_MELT_CAL_FILENAME      1071
#define IDC_RADIO_FILTER_2              1072
#define IDC_EDIT_NAME                   1072
#define IDC_EDIT_FINAL_TEMP_CAL_FILENAME 1072
#define IDC_RADIO_FILTER_3              1073
#define IDC_EDIT_CYCLES                 1073
#define IDC_EDIT_CAPSENSE_CAL_FILENAME  1073
#define IDC_RADIO_FILTER_4              1074
#define IDC_STATIC_PROGRAM_FRAME        1074
#define IDC_EDIT_CAPSENSE_FULL_FILENAME 1074
#define IDC_RADIO_FILTER_5              1075
#define IDC_EDIT_FINAL_CAL_FILENAME     1075
#define IDC_COMBO_COLOR                 1076
#define IDC_EDIT_CAL_FULL_FILENAME      1076
#define IDC_STATIC_TEMP2                1077
#define IDC_STATIC_NUMBER1_UNIT         1077
#define IDC_EDIT_SYSTEM_CONFIGURATION_REPORT 1077
#define IDC_STATIC_TEMP1                1078
#define IDC_STATIC_NUMBER1_LABEL        1078
#define IDC_EDIT_CONFIG_REPORT_FULL_FILENAME 1078
#define IDC_STATIC_TIME1                1079
#define IDC_STATIC_NUMBER2_LABEL        1079
#define IDC_EDIT_BURN_IN_REPORT_FOLDER  1079
#define IDC_STATIC_TIME2                1080
#define IDC_STATIC_NUMBER2_UNIT         1080
#define IDC_EDIT_BURN_IN_REPORT_FILENAME 1080
#define IDC_STATIC_COLOR                1081
#define IDC_EDIT_OUTPUT_FILENAME        1082
#define IDC_COMBO_TEMP_MODEL            1082
#define IDC_BUTTON_GET_PATH             1083
#define IDC_STATIC_TEMP_MODEL           1083
#define IDC_CHECK_CAPTURE_IMAGES        1084
#define IDC_STATIC_NUMBER3_LABEL        1084
#define IDC_STATIC_NUMBER4_LABEL        1085
#define IDC_STATIC_NUMBER3_UNIT         1086
#define IDC_STATIC_NUMBER4_UNIT         1087
#define IDC_STATIC_NUMBER5_UNIT         1088
#define IDC_STATIC_NUMBER6_UNIT         1089
#define IDC_STATIC_NUMBER7_UNIT         1090
#define IDC_EDIT_STRING1                1091
#define IDC_STATIC_STRING1              1092
#define IDC_EDIT_STRING2                1093
#define IDC_STATIC_STATUS               1094
#define IDC_STATIC_STRING2              1094
#define IDC_STATIC_NUMBER8_UNIT         1095
#define IDC_COMBO_ILLUM_COLOR           1101
#define IDC_COMBO_FILTER_COLOR          1102
#define IDC_PROGRESS                    1103
#define IDC_BUTTON_CALIBRATE            1104
#define IDC_EDIT_XOFFSET                1105
#define IDC_EDIT_YOFFSET                1106
#define IDC_EDIT_LOG_FILENAME           1106
#define IDC_EDIT_SPACING                1107
#define IDC_BUTTON_BROWSE               1107
#define IDC_EDIT_RADIUS                 1108
#define IDC_CHECK_ENABLE_LOGGING        1108
#define IDC_CHECK_ENABLE_PWM_LOGGING    1109
#define IDC_PROGRESS_PROTOCOL           1111
#define IDC_EDIT_IMAGE_NUMBER           1116
#define IDC_SPIN_IMAGE_NUMBER           1117
#define IDC_CHECK_SHOW_MASK             1119
#define IDC_CHECK_INTENSITY             1120
#define IDC_EDIT_INTENSITY_LOWER_LIMIT  1121
#define IDC_SPIN_INTENSITY_LOWER_LIMIT  1122
#define IDC_EDIT_INTENSITY_UPPER_LIMIT  1123
#define IDC_SPIN_INTENSITY_UPPER_LIMIT  1124
#define IDC_CHECK_SAVE_IMAGES           1125
#define IDC_BUTTON_UPGRADE              1127
#define IDC_BUTTON_UPGRADE_FIRMWARE     1127
#define IDC_BUTTON_CALIBRATION          1128
#define IDC_BUTTON_UPGRADE_FPGA         1129
#define IDC_COMBO_CHANNEL               1133
#define IDC_COMBO_CALPOINT              1134
#define IDC_EDIT_CALTEMP                1135
#define IDC_EDIT_LINE_NUMBER            1135
#define IDC_EDIT_MIN_WELL               1135
#define IDC_BUTTON_SAVE_CAL             1136
#define IDC_EDIT_ERROR_COUNT            1136
#define IDC_EDIT_MIN_WELL_RAW           1136
#define IDC_BUTTON_EXPORT               1137
#define IDC_EDIT_MIN_WELL_PERCENT       1137
#define IDC_BUTTON_LOAD_CAL             1138
#define IDC_BUTTON_INIT_SYSTEM          1138
#define IDC_EDIT_MAX_WELL               1138
#define IDC_BUTTON_OPEN_DOOR            1139
#define IDC_EDIT_MAX_WELL_RAW           1139
#define IDC_BUTTON_CLOSE_DOOR           1140
#define IDC_EDIT_MAX_WELL_PERCENT       1140
#define IDC_BUTTON_RAISE_LID            1141
#define IDC_BUTTON_LOWER_LID            1142
#define IDC_BUTTON_OPEN_CAVITY          1143
#define IDC_BUTTON_CLOSE_CAVITY         1144
#define IDC_BUTTON_SELF_TEST            1145
#define IDC_STATIC_FW_VER_STR           1146
#define IDC_STATIC_FW_BUILD_DATE        1147
#define IDC_STATIC_VERSION_LABEL        1148
#define IDC_STATIC_BUILD_DATE_LABEL     1149
#define IDC_STATIC_FILE_NAME            1150
#define IDC_STATIC_BUILD_DATE_LABEL2    1150
#define IDC_STATIC_FILE_STATE           1151
#define IDC_STATIC_FW_BUILD_DATE2       1151
#define IDC_CHECK_POLL_STATUS           1152
#define IDC_LIST_STATUS                 1157
#define IDC_EDIT_NUMBER1                1158
#define IDC_EDIT_NUMBER2                1159
#define IDC_EDIT_NUMBER3                1160
#define IDC_BUTTON_DISABLE_LID          1160
#define IDC_EDIT_NUMBER4                1161
#define IDC_BUTTON_DISABLE_BLOCK        1161
#define IDC_EDIT_NUMBER5                1162
#define IDC_BUTTON_CANCEL               1163
#define IDC_EDIT_NUMBER6                1163
#define IDC_COMBO_SAVE_IMAGES           1164
#define IDC_EDIT_NUMBER7                1164
#define IDC_EDIT_NUMBER8                1165
#define IDC_LIST_TEST_STATUS            1168
#define IDC_STATIC_TEST_STATE           1170
#define IDC_PROGRESS_TEST               1171
#define IDC_STATIC_PWR_DOWN_REQUESTED   1174
#define IDC_COMBO_FPGACOMMPORT          1175
#define IDC_COMBO_PCBCOMMPORT           1176
#define IDC_STATIC_FPGA_FW_VER_STR      1177
#define IDC_STATIC_FPGA_FW_VERSION_LABEL 1178
#define IDC_STATIC_FPGA_FW_BUILD_DATE_LABEL 1179
#define IDC_STATIC_FPGA_FW_BUILD_DATE   1180
#define IDC_STATIC_FPGA_VERSION_LABEL   1181
#define IDC_PROGRESS_BAR                1181
#define IDC_STATIC_FPGA_VER_STR         1182
#define IDC_CHECK_CONTINUE_ON_ERROR     1182
#define IDC_STATIC_PCB_FW_VERSION_LABEL 1183
#define IDC_STATIC_PCB_FW_BUILD_DATE_LABEL 1184
#define IDC_EDIT_STATUS                 1184
#define IDC_STATIC_PCB_FW_VER_STR       1185
#define IDC_BUTTON_PAUSE                1185
#define IDC_STATIC_PCB_FW_BUILD_DATE    1186
#define IDC_BUTTON_DEVICE_TEST          1186
#define IDC_CHECK_VERBOSE               1187
#define IDC_BUTTON_PERFORMANCE_TEST     1188
#define IDC_BUTTON_CAPTURE_FPGA_MEMORY  1189
#define IDC_BUTTON_FILE_NAMING_TOOL     1190
#define IDC_RADIO_PCR                   1191
#define IDC_DATA_GRID                   1191
#define IDC_GRID_IMAGE_DATA             1191
#define IDC_CHECK_PERCENT_OF_MAX        1192
#define IDC_CHECK_SHOW_CROSSHAIRS       1192
#define IDC_CHECK_SHOW_IMAGE            1192
#define IDC_CHECK_MONITOR_CONNECTION    1192
#define IDC_CHECK_PAUSE                 1193
#define IDC_SPIN_EDIT_ERROR_THRESHOLD   1194
#define IDC_BUTTON_CAMERA_START         1195
#define IDC_BUTTON_CAMERA_STOP          1196
#define IDC_STATIC_RACHIS_CONFIG_FRAME  1196
#define IDC_RADIO_OVERLAY_NONE          1197
#define IDC_RADIO_OVERLAY_PCR_MASK      1198
#define IDC_RADIO_OVERLAY_SDA_MASK      1199
#define IDC_STATIC_CONFIG_INSTALLED_PACKAGE 1199
#define IDC_RADIO_OVERLAY_INTENSITY     1200
#define IDC_RADIO_OVERLAY_CROSSHAIR     1201
#define IDC_PROGRESS1                   1205
#define IDC_PROGRESS_STATUS             1205
#define IDC_RADIO_ELECTROFORM           1206
#define IDC_BUTTON_CALIBRATE_USING_IMAGE 1207
#define ID_BUTTON_SAVE                  1209
#define IDC_STATIC_PCR_MASK_CONFIGURATION 1211
#define IDC_STATIC_SDA_MASK_CONFIGURATION 1212
#define IDC_STATIC_LOG_LEVEL            1213
#define IDC_STATIC_RUN_IMAGE_CAPTURE_TYPE 1214
#define IDC_STATIC_DATA_RETENTION_TIME  1215
#define IDC_STATIC_GEO_CORRECTION       1216
#define IDC_STATIC_SHUTDOWN_TIME        1217
#define IDC_BUTTON1                     1218
#define IDC_BUTTON_SAVE_CONFIGURATION   1218
#define IDC_BUTTON_LOAD_IMAGE           1218
#define IDC_BUTTON_FILL_DATE_TIME       1218
#define IDC_BUTTON_CAPTURE_DEBUG_OUTPUT 1218
#define IDC_STATIC_IP_ADDR              1222
#define IDC_STATIC_SCRIPT_FILE_NAME     1223
#define IDC_STATIC_LOG_FILE_NAME        1224
#define IDC_STATIC_HD_IMAGE_VERSION     1225
#define IDC_STATIC_CONFIGURED           1226
#define IDC_STATIC_CONFIGURED_MSG       1226
#define IDC_STATIC_HD_IMAGE_VERSION2    1226
#define IDC_STATIC_SYSTEM_SERIAL_NUMBER 1226
#define IDC_CHECK1                      1227
#define IDC_CHECK2                      1228
#define IDC_BUTTON_IMAGE_PREV           1228
#define IDC_CHECK3                      1229
#define IDC_BUTTON3                     1229
#define IDC_BUTTON_IMAGE_NEXT           1229
#define IDC_CHECK4                      1230
#define IDC_STATIC_IMAGE_FILENAME       1230
#define IDC_RADIO_INITIAL               1231
#define IDC_EDIT_MELT_PLATE_UID         1240
#define IDC_EDIT_OPERATOR_INITIALS      1241
#define IDC_EDIT_YEAR                   1242
#define IDC_EDIT_MONTH                  1243
#define IDC_EDIT_DAY                    1244
#define IDC_EDIT_HOUR                   1245
#define IDC_EDIT_SECOND                 1246
#define IDC_EDIT_MINUTE                 1247
#define IDC_BUTTON_MELT_CAL_FILENAME    1248
#define IDC_BUTTON_FINAL_TEMP_CAL_FILENAME 1249
#define IDC_BUTTON_CAPSENSE_CAL_FILENAME 1250
#define IDC_BUTTON_CAPSENSE_FULL_FILENAME 1251
#define IDC_BUTTON_FINAL_CAL_FILENAME   1252
#define IDC_BUTTON_CAL_FULL_FILENAME    1253
#define IDC_BUTTON_SYSTEM_CONFIGURATION_REPORT 1254
#define IDC_BUTTON_CONFIG_REPORT_FULL_FILENAME 1255
#define IDC_BUTTON_BURN_IN_REPORT_FOLDER 1256
#define IDC_BUTTON_BURN_IN_REPORT_FILENAME 1257
#define IDC_STATIC_INSTRUMENT_SERIAL_NUMBER 1258
#define IDC_STATIC_BLOCK_SERIAL_NUMBER  1259
#define IDC_BUTTON_DEBUG_CAPTURE        1261
#define IDC_EDIT_DEBUG_OUTPUT           1262
#define IDC_EDIT_BYTE_COUNT             1263
#define IDC_PROGRESS_DOWNLOAD           1264
#define IDC_BUTTON2                     1265
#define IDC_BUTTON_COPY_TO_CLIPBOARD    1265
#define IDC_COMBO_CHEM_CAL              1266

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1266
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
